# Generated by Django 4.1.7 on 2023-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0002_rename_profile_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='John Doe (Default)', max_length=200, null=True),
        ),
    ]
