# Generated by Django 4.1.7 on 2023-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0003_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.CharField(default='DefAULT', max_length=200, null=True),
        ),
    ]
