# Generated by Django 4.1.7 on 2023-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0004_product_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_link',
            field=models.CharField(default='ulr of image', max_length=200, null=True),
        ),
    ]
