# Generated by Django 4.1.7 on 2023-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0006_alter_product_title_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
