# Generated by Django 4.1.7 on 2023-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0007_remove_product_user_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_link',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Hello'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
