# Generated by Django 4.1.7 on 2023-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0008_remove_product_title_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='myntra_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='myntra_price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
