# Generated by Django 4.1.7 on 2023-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esites', '0009_remove_product_price_product_amazon_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(default='https://www.amazon.in/', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(decimal_places=2, default=299, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='All Product Are good'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flipkart_link',
            field=models.CharField(default='https://www.flipkart.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='flipkart_price',
            field=models.DecimalField(decimal_places=2, default=499, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='myntra_link',
            field=models.CharField(default='https://www.flipkart.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='myntra_price',
            field=models.DecimalField(decimal_places=2, default=149, max_digits=8),
        ),
    ]
